services:
  postgres:
    image: postgres:15
    container_name: nestjs-blueprint-crud-postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestjs_crud_example
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: